### PR TITLE
Safer algorithms to allocate VxLAN id

### LINKED ISSUE #51: VxLAN ID Allocation algorithm is not safe
If for some reason, (etcd lock failure, as it happened because the lib was broken) two Network get the same ID N, all the following Network will get the N+1 ID, forever.

### PR DESCRIPTION
**Pull request by Soulou**
Fixes #51

### CODE REVIEW

File: idmanager/idmanager.go [hunk 1]
```diff
@@ -62,18 +61,17 @@ func (m *manager) Generate(ctx context.Context) (int, error) {
 		return -1, errors.Wrapf(err, "fail to get list of items with prefix %s from store", m.prefix)
 	}
 
-	var ids []int
+	ids := map[int]bool{}
```
Comment (johnsudaar) [inline idmanager/idmanager.go]: Why this change was there an error ?

If yes, could you write a specs for this error ?

Comment (Soulou) [reply idmanager/idmanager.go]: The behavior was described here: https://github.com/Scalingo/sand/issues/51

I'll add a test about it

**Comment by Soulou** [comment]
Old algorithm:

```
┌[leo☮soulou7]-(~/Projects/Go/src/github.com/Scalingo/sand)-[git://14a77fd ✗]-
└> go test -v ./idmanager
=== RUN   TestManager_Generate
=== RUN   TestManager_Generate/when_no_item,_it_should_return_1,_then_2
=== RUN   TestManager_Generate/when_1_is_present,_it_should_return_2,_then_3
=== RUN   TestManager_Generate/when_2_and_3_are_present,_it_should_return_1,_then_4
=== RUN   TestManager_Generate/when_1_is_present_twice_(data_anomaly),_it_shouhld_return_2,_then_3
=== RUN   TestManager_Generate/when_listing_fails,_it_should_return_an_error
--- FAIL: TestManager_Generate (0.00s)
    --- PASS: TestManager_Generate/when_no_item,_it_should_return_1,_then_2 (0.00s)
    --- PASS: TestManager_Generate/when_1_is_present,_it_should_return_2,_then_3 (0.00s)
    --- PASS: TestManager_Generate/when_2_and_3_are_present,_it_should_return_1,_then_4 (0.00s)
    --- FAIL: TestManager_Generate/when_1_is_present_twice_(data_anomaly),_it_shouhld_return_2,_then_3 (0.00s)
        Error Trace:    idmanager_test.go:87
        Error:      	Not equal: 
                    	expected: 3
                    	actual  : 2
        Test:       	TestManager_Generate/when_1_is_present_twice_(data_anomaly),_it_shouhld_return_2,_then_3
    --- PASS: TestManager_Generate/when_listing_fails,_it_should_return_an_error (0.00s)
FAIL
FAIL	github.com/Scalingo/sand/idmanager	0.004s
FAIL
```

New algorithm:

```
┌[leo☮soulou7]-(~/Projects/Go/src/github.com/Scalingo/sand)-[git://fix/51/id-gen ✗]-
└> go test -v ./idmanager
=== RUN   TestManager_Generate
=== RUN   TestManager_Generate/when_no_item,_it_should_return_1,_then_2
=== RUN   TestManager_Generate/when_1_is_present,_it_should_return_2,_then_3
=== RUN   TestManager_Generate/when_2_and_3_are_present,_it_should_return_1,_then_4
=== RUN   TestManager_Generate/when_1_is_present_twice_(data_anomaly),_it_shouhld_return_2,_then_3
=== RUN   TestManager_Generate/when_listing_fails,_it_should_return_an_error
--- PASS: TestManager_Generate (0.00s)
    --- PASS: TestManager_Generate/when_no_item,_it_should_return_1,_then_2 (0.00s)
    --- PASS: TestManager_Generate/when_1_is_present,_it_should_return_2,_then_3 (0.00s)
    --- PASS: TestManager_Generate/when_2_and_3_are_present,_it_should_return_1,_then_4 (0.00s)
    --- PASS: TestManager_Generate/when_1_is_present_twice_(data_anomaly),_it_shouhld_return_2,_then_3 (0.00s)
    --- PASS: TestManager_Generate/when_listing_fails,_it_should_return_an_error (0.00s)
PASS
ok  	github.com/Scalingo/sand/idmanager	0.004s
```
```
