### PR TITLE
Fix/271/issue with starting the service since graceful udate

### LINKED ISSUE #271: Issue with starting the service since `go-utils/graceful` update
Since https://github.com/Scalingo/sand/pull/269

We get the following error at start of the service:

```log
sand-web-1     | [00] INFO[2024-07-19T10:17:34.109] Listening                                     port=9999
sand-web-1     | [00] INFO[2024-07-19T10:17:34.109] Enabling docker plugin                        port=9998
sand-web-1     | [00] ERRO[2024-07-19T10:17:34.112] fail to intialize docker plugin listener      error="creating tableflip upgrader: tableflip: only a single Upgrader allowed"
```

Tableflip has been implemented by the update of `go-utils/graceful` package: https://github.com/Scalingo/sand/pull/269/files#diff-b23955474deda99331ce8c459e35a3d30f09652fcafab972bcc787756c4c2b1fR7

Related PR on go-utils: https://github.com/Scalingo/go-utils/pull/909

Usage of tableflip is not the same as previous package (`grace`) and cannot be created multiple times for different ports allocation.

### PR DESCRIPTION
**Pull request by sc-zenokerr**
Fixes #271 
Related to https://github.com/Scalingo/go-utils/pull/944
Related to STORY-828

### CODE REVIEW

File: cmd/sand-agent/sand-agent.go [hunk 1]
```diff
@@ -94,22 +93,36 @@ func main() {
...
+	sandRouter.HandleFunc("/networks/{id}", nctrl.Connect).Methods("CONNECT")
+	sandRouter.HandleFunc("/endpoints", ectrl.Create).Methods("POST")
+	sandRouter.HandleFunc("/endpoints", ectrl.List).Methods("GET")
+	sandRouter.HandleFunc("/endpoints/{id}", ectrl.Destroy).Methods("DELETE")
 
 	log.WithField("port", c.HttpPort).Info("Listening")
 	serviceEndpoint := fmt.Sprintf(":%d", c.HttpPort)
 
-	wg := &sync.WaitGroup{}
+	// We can only have one graceful service per process
```
Comment (SCedricThomas) [inline cmd/sand-agent/sand-agent.go:111]: suggestion: Would it be possible to add more context it?
```suggestion
	// We can only have one graceful service per process since graceful 1.2.0
```

**Review by SCedricThomas — COMMENTED** [review]
Otherwise LGTM

**Review by Soulou — APPROVED** [review]
Tested with success
